### ISSUE TITLE
JSON decoding error. Reason: badarg while running dynamic configuration

### ISSUE THREAD

**Issue by jugglingjassi** [cloudamqp/rabbitmq-vshovel#7]
I tried to set the configurations by executing the following command in Rabbit MQ command prompt:

rabbitmqctl set_parameter vshovel my-vshovel \
  '{"src-uri": "amqp://guest:guest@localhost:5672/",
    "src-queue": "pmo", "dest-type":"http",
    "dest-uri":"http://localhost:5556/api/resource/new", "dest-vsn": "1.1",
    "dest-args": {"method": "post", "keep_alive_timeout" : 10000}}'

The following error is being thrown:
'Setting runtime parameter "vshovel" for component "my-vshovel" to "\" in vhost "/" ...
Error:
JSON decoding error. Reason: badarg

I'm new to RabbitMQ and is looking for a way to call Web API methods on incoming messages on RabbitMQ queues.

Can you please help identify what am I doing wrong in setup?

**Comment by Ayanda-D** [comment]
@jugglingjassi what OS are you on? Your text editor you've copied your config from might also be messing up some characters (like \n). The following works on my Mac;

```
rabbitmqctl set_parameter vshovel my-vshovel '{"src-uri": "amqp://guest:guest@localhost:5672/", "src-queue": "pmo", "dest-type":"http", "dest-uri":"http://localhost:5556/api/resource/new", "dest-vsn": "1.1", "dest-args": {"method": "post", "keep_alive_timeout" : 10000}}'
```

**Comment by Ayanda-D** [comment]
> I'm new to RabbitMQ and is looking for a way to call Web API methods on incoming messages on RabbitMQ queues.

& sure, based on your config, this plugin will POST messages from your "pmo" queue to your HTTP endpoint, "http://localhost:5556/api/resource/new" 👍

**Comment by jugglingjassi** [comment]
I'm using Windows OS and pasted the config text carefully without line breaks. The previous error went away but I got the following error:

Error (argument validation): too many arguments.
Arguments given:
        set_parameter vshovel my-vshovel1 '{src-uri: amqp://guest:guest@localhost:5672/, src-queue: pmo, dest-type:http, dest-uri:http://localhost:5556/api/resource/new, dest-vsn: 1.1, dest-args: {method: post, keep_alive_timeout : 10000}}'
Usage:
rabbitmqctl [-n <node>] [-t <timeout>] [-q] set_parameter [-p <vhost>] <component_name> <name> <value>

I really hope this plugin works for my scenario. I need to set up one endpoint per queue which will handle the data processing further. The endpoint API where the payload data will be forwarded to will need authentication as well. So, I'll need to accommodate that too. As you said in other issue response, probably using X- headers. 

Do you have the documentation for this ready? I have already started writing a console application in Python to handle forwarding queue data to REST endpoints but I'd love to use this plugin and save time to write better APIs.

**Comment by Ayanda-D** [comment]
@jugglingjassi OKAY, you're on Windows. Generally, specifying JSON config on windows command line will always differ regardless of what system you're working on/with. Use the following:

```
rabbitmqctl set_parameter -p / vshovel my-vshovel "{""src-uri"": ""amqp://guest:guest@localhost:5672/%2f"", ""src-queue"": ""pmo"", ""dest-type"":""http"", ""dest-uri"":""http://localhost:5556/api/resource/new"", ""dest-vsn"": ""1.1"", ""dest-args"": {""method"": ""post"", ""keep_alive_timeout"":10000}}"
```
And make sure you abide to the [AMQP-URI specification](https://www.rabbitmq.com/uri-spec.html), especially on the VHOST part. I've also added an example for Windows users https://github.com/cloudamqp/rabbitmq-vshovel/commit/c439a10efdc518eb930dcccdd0a7334f1ca859ce. And yes, indeed, you may pass and propagate custom headers as discussed in https://github.com/cloudamqp/rabbitmq-vshovel/issues/3#issuecomment-309413988. Also consider using the [static configuration](https://github.com/cloudamqp/rabbitmq-vshovel#static-configuration) option, if your queue is going to be static in nature, for entire lifespan of your messaging layer. And if starting out with Rabbit, I recommend some excellent [tutorials from CloudAMQP](https://www.cloudamqp.com/blog/2015-05-21-part2-3-rabbitmq-for-beginners_example-and-sample-code-python.html).

Regarding extensive documentation, as mentioned, its on the cards, project being sponsored by the aforementioned [organisations](https://github.com/cloudamqp/rabbitmq-vshovel#license-and-copyright), significant advancements are introduced following internal "green-light" signals. However, we reckon what we currently have in place along with [RabbitMQ plugin](https://www.rabbitmq.com/plugins.html) usage docs is definitely more than sufficient for its usage and primary purpose. And obviously feedback from valued users like yourself, with contributions are always more than welcome 😉The config i've mentioned above should fix your issue 👍
